const format = require('date-fns/format')
const faker = require('faker')

for (i = 0; i < 100; i++) {
  let name = faker.name.firstName()
  let last = faker.name.lastName()
  let email = faker.internet.email()
  let region = faker.fake(
    '{"country": "{{address.country}}", "province": "{{address.state}}", "canton": "{{address.city}}"}'
  )
  let sex = faker.random.arrayElement([0, 1, 2, 9])
  let date = format(faker.date.past(40, '2000-01-01'), 'YYYY-MM-DD')

  console.log(`('${name}','${last}','${email}','${region}',${sex},'${date}'),`)
}

// INSERT INTO
//   med_img.Patient(given_name, family_name, email, region, sex, birthdate)
// VALUES
// ('Veronica','Koepp','Amir54@hotmail.com','{"country": "Bahrain", "province": "Iowa", "canton": "New Mertie"}',9,'1973-10-28'),
// ('Guillermo','Jacobson','Rosie.Schaden@gmail.com','{"country": "Lebanon", "province": "New York", "canton": "East Margot"}',9,'1968-08-24'),
// ('Karley','Hermiston','Destany_Schulist66@gmail.com','{"country": "Montserrat", "province": "Maryland", "canton": "Bednarview"}',9,'1964-09-21'),
// ('Jerrell','King','Clemmie.Schaefer23@hotmail.com','{"country": "Gabon", "province": "Indiana", "canton": "Theresiaport"}',9,'1986-05-18'),
// ('Rowan','Hickle','Barry97@yahoo.com','{"country": "Guam","province": "Louisiana", "canton": "West Kasandratown"}',9,'1996-03-16'),
// ('Felton','Borer','Misael_Veum@hotmail.com','{"country": "Turkey", "province": "New Jersey", "canton": "Lorenaborough"}',2,'1988-11-30'),
// ('Delfina','Stamm','Mckenzie73@hotmail.com','{"country": "Dominican Republic", "province": "Rhode Island", "canton": "Lynchhaven"}',9,'1993-09-07'),
// ('Rossie','Barrows','Catherine39@hotmail.com','{"country":"Canada", "province": "Indiana", "canton": "South Jamie"}',9,'1960-12-27'),
// ('Xzavier','Gusikowski','Rylan_Kunze68@yahoo.com','{"country": "Mayotte", "province": "South Dakota", "canton": "South Ryley"}',9,'1968-09-06'),
// ('Macie','VonRueden','Helga_Schiller81@hotmail.com','{"country": "Democratic People''s Republic of Korea", "province":"Illinois", "canton": "Ratkemouth"}',2,'1986-04-27'),
// ('Earline','Witting','Scarlett78@gmail.com','{"country": "Haiti", "province": "Louisiana", "canton": "Grantfort"}',0,'1976-04-03'),
// ('Bianka','Rempel','Vito_Labadie84@hotmail.com','{"country": "Armenia", "province": "Arkansas", "canton": "West Kavonburgh"}',2,'1963-05-07'),
// ('Dariana','Zulauf','Arely61@hotmail.com','{"country": "Mayotte", "province": "North Dakota", "canton": "Jastfort"}',1,'1967-08-19'),
// ('Emmet','Eichmann','Jerald_Kub58@yahoo.com','{"country": "Moldova", "province": "New York", "canton": "Willfurt"}',0,'1988-09-15'),
// ('Domenico','Hackett','Rhea_Ward@gmail.com','{"country": "Morocco", "province": "Nevada", "canton": "Lake Kenya"}',2,'1977-07-25'),
// ('Madelyn','Kub','Marina_Nitzsche20@yahoo.com','{"country": "Cuba", "province": "Kentucky", "canton": "Port Maxwell"}',9,'1994-09-26'),
// ('Leonor','O''Hara','Bradley27@gmail.com','{"country": "Equatorial Guinea", "province": "Montana", "canton": "Trinitychester"}',9,'1970-05-07'),
// ('Ayla','Schinner','Clotilde58@gmail.com','{"country": "Turks and Caicos Islands", "province": "Florida", "canton": "Dollyshire"}',2,'1996-06-09'),
// ('Florian','Moen','Geoffrey.Bruen73@gmail.com','{"country": "Aruba", "province": "Alabama", "canton": "East Chasityton"}',1,'1972-02-06'),
// ('Carleton','Sauer','Paxton_Denesik45@yahoo.com','{"country": "Netherlands", "province": "Alaska", "canton": "Benjaminton"}',2,'1986-04-06'),
// ('Elmore','Sawayn','Bruce.Windler33@yahoo.com','{"country": "Jordan", "province": "West Virginia", "canton": "Port Katlyn"}',2,'1964-02-20'),
// ('Destin','Botsford','Malika.Dach92@gmail.com','{"country": "Costa Rica", "province": "Nebraska", "canton": "Jovaniburgh"}',1,'1975-01-09'),
// ('Kayley','Kunze','Favian.Hartmann83@hotmail.com','{"country": "Congo", "province": "Missouri", "canton": "East Einoborough"}',0,'1970-12-22'),
// ('Jacinto','Bogisich','Wyman.Koch@hotmail.com','{"country": "Somalia", "province": "Nevada", "canton": "Lockmanbury"}',9,'1996-12-24'),
// ('Conner','Kuhic','Jordyn84@yahoo.com','{"country": "Bosnia and Herzegovina", "province": "New Hampshire", "canton": "Russelland"}',2,'1975-05-18'),
// ('Tess','Homenick','Otilia.Gleichner@hotmail.com','{"country": "Madagascar", "province": "Florida", "canton": "West Florianstad"}',0,'1988-02-28'),
// ('Julie','Ziemann','Hoyt_Corwin@hotmail.com','{"country": "Guinea", "province": "Tennessee", "canton": "Runolfsdottirburgh"}',0,'1990-08-30'),
// ('Garret','Walsh','Derek_Jones@gmail.com','{"country": "Bouvet Island (Bouvetoya)", "province": "South Dakota", "canton": "South Rico"}',1,'1979-10-29'),
// ('Trevion','Robel','Buck_Weber@gmail.com','{"country": "Turks and Caicos Islands", "province": "Minnesota", "canton":"Codyfort"}',2,'1984-09-01'),
// ('Dariana','Von','Lisandro_Cassin57@gmail.com','{"country": "Costa Rica", "province": "Maryland", "canton": "East Monteborough"}',9,'1961-08-02'),
// ('Ezekiel','Gerlach','Jacey_Lind82@yahoo.com','{"country":"Latvia", "province": "Washington", "canton": "Jacobsfurt"}',9,'1997-09-13'),
// ('Grady','Gulgowski','Rubie_Homenick78@hotmail.com','{"country": "Singapore", "province": "Rhode Island", "canton": "Lake Carmelastad"}',9,'1973-04-13'),
// ('Carolanne','Runolfsson','Luther_Johnston65@hotmail.com','{"country": "Micronesia", "province": "Louisiana", "canton": "Port Darron"}',9,'1976-08-01'),
// ('Orlo','Brown','Gerard.Jacobson@hotmail.com','{"country":"Lebanon", "province": "South Carolina", "canton": "West Lawsonberg"}',2,'1987-11-07'),
// ('Chad','Gusikowski','Bethany_Muller12@hotmail.com','{"country": "Hungary", "province": "New Jersey", "canton": "Pricebury"}',1,'1970-01-29'),
// ('Avery','Stamm','Lora.Abbott69@hotmail.com','{"country": "El Salvador", "province": "Pennsylvania", "canton": "Douglastown"}',9,'1972-08-19'),
// ('Dameon','Stanton','Karlie72@yahoo.com','{"country": "Oman", "province": "New York", "canton": "Port Ivory"}',0,'1978-05-05'),
// ('Kellie','Hessel','Broderick81@gmail.com','{"country": "Burkina Faso", "province": "Kansas", "canton": "Robertsberg"}',9,'1988-06-14'),
// ('Oleta','Rutherford','Jeffrey_Anderson@yahoo.com','{"country": "Namibia", "province": "Delaware", "canton": "Georgeton"}',9,'1991-08-04'),
// ('Felipa','Donnelly','Carrie19@gmail.com','{"country": "Kuwait", "province": "Hawaii", "canton": "North Daphnee"}',0,'1986-04-27'),
// ('Lenny','Labadie','Wilmer_Von37@yahoo.com','{"country": "Slovenia", "province": "Maryland", "canton": "Port Stuartton"}',0,'1994-10-04'),
// ('Elda','Rippin','Tony_Bergnaum@gmail.com','{"country": "United States of America", "province": "Oklahoma", "canton":"Joeyville"}',0,'1987-09-28'),
// ('Kathleen','Ernser','Retta.Medhurst@yahoo.com','{"country": "Bulgaria", "province": "Illinois", "canton": "Port Haroldfort"}',2,'1967-12-16'),
// ('Fernando','Kessler','Weston.Spinka6@hotmail.com','{"country": "Bulgaria", "province": "Maine", "canton": "Treutelburgh"}',2,'1965-05-21'),
// ('Jasen','Johns','Jamarcus37@gmail.com','{"country": "Belgium", "province": "Oklahoma", "canton": "Keontown"}',1,'1991-08-26'),
// ('Paula','Hermann','Alia.Bode7@gmail.com','{"country": "Solomon Islands", "province": "Colorado", "canton": "North Franciscochester"}',1,'1995-02-28'),
// ('Elmore','Labadie','Aimee53@gmail.com','{"country": "Cayman Islands", "province": "South Dakota", "canton": "New Johathanfurt"}',0,'1999-09-06'),
// ('Brayan','Ledner','Stanley44@gmail.com','{"country": "Tuvalu", "province": "Colorado", "canton": "New Murlview"}',1,'1983-07-01'),
// ('Keshaun','Turner','Elisha.Cruickshank96@gmail.com','{"country": "Mongolia", "province": "Georgia", "canton": "Port Cadeview"}',0,'1965-04-23'),
// ('Retta','Sauer','Ramon98@yahoo.com','{"country": "Dominica", "province": "Pennsylvania", "canton": "South Andreane"}',9,'1990-08-02'),
// ('Rowan','Wolff','Chloe.Ortiz@hotmail.com','{"country": "New Caledonia", "province": "Utah", "canton": "Edwinaland"}',0,'1996-12-20'),
// ('Oral','Bailey','Ila_Spinka52@hotmail.com','{"country": "New Caledonia", "province": "Georgia", "canton": "Lake Casimir"}',2,'1983-10-27'),
// ('Savannah','White','Shea.Gorczany86@hotmail.com','{"country": "Saint Martin", "province": "Washington", "canton": "Hettingerfurt"}',9,'1961-06-20'),
// ('Adell','Lueilwitz','Jerald.Douglas@gmail.com','{"country": "Latvia", "province": "California", "canton": "Denesikchester"}',0,'1961-07-14'),
// ('Sigrid','Schumm','Aubree12@hotmail.com','{"country": "Maldives", "province": "New Jersey", "canton": "Pourosside"}',0,'1965-05-12'),
// ('Manuel','Reynolds','Jude.Runolfsdottir91@yahoo.com','{"country": "Croatia", "province": "Maryland", "canton": "Turnermouth"}',2,'1984-08-05'),
// ('Ladarius','Lehner','Jeromy.Larkin@hotmail.com','{"country": "Guinea-Bissau", "province": "Connecticut", "canton": "Brianaland"}',1,'1970-03-02'),
// ('Ayden','Torp','Maci_Rempel38@yahoo.com','{"country": "Hong Kong", "province": "Virginia", "canton": "Port Clementhaven"}',9,'1998-05-23'),
// ('Nichole','Kessler','Ryan94@yahoo.com','{"country": "Uzbekistan", "province": "North Carolina", "canton": "Antoinettechester"}',0,'1988-07-27'),
// ('Carlos','Beer','Delaney37@yahoo.com','{"country": "Norfolk Island", "province": "Alabama", "canton": "Port Zackeryport"}',0,'1966-11-10'),
// ('Connie','Quigley','Regan.Reinger81@yahoo.com','{"country": "Sudan", "province": "Montana", "canton": "Elenamouth"}',9,'1989-07-10'),
// ('Herman','Mante','Kraig41@gmail.com','{"country": "Gabon", "province": "Kansas", "canton": "Port Leann"}',0,'1967-06-20'),
// ('Kasey','Homenick','Cesar_Shanahan71@gmail.com','{"country": "Trinidad and Tobago", "province": "South Dakota", "canton": "Vedamouth"}',9,'1986-10-08'),
// ('Ardella','Leuschke','Mack.Bechtelar81@hotmail.com','{"country": "Brazil", "province": "Iowa", "canton": "Lemketown"}',9,'1982-07-14'),
// ('Tyrel','Ebert','Clinton89@yahoo.com','{"country": "Pakistan", "province": "Vermont", "canton": "East Pedro"}',1,'1986-12-22'),
// ('Rosina','Kuhn','Naomie.Bogan97@yahoo.com','{"country": "Guinea-Bissau", "province": "Missouri", "canton": "O''Connellmouth"}',0,'1997-03-09'),
// ('Agnes','Keeling','Alice.Leuschke45@hotmail.com','{"country": "Lithuania", "province": "Wisconsin", "canton": "Wisozkside"}',1,'1961-01-18'),
// ('Chauncey','Wehner','Glenna_Kovacek74@hotmail.com','{"country": "Georgia", "province": "Kansas", "canton": "Port Edwardoside"}',2,'1978-01-02'),
// ('Emery','Olson','Emerald.Berge@yahoo.com','{"country": "Iceland", "province": "California", "canton": "Anabelmouth"}',9,'1984-04-23'),
// ('Rossie','Mann','Irving.Hane@gmail.com','{"country": "Canada", "province": "North Carolina", "canton": "West Cristina"}',0,'1962-09-14'),
// ('Gilbert','Kozey','Hassan39@yahoo.com','{"country": "Cyprus", "province": "Utah", "canton": "Celestinofort"}',1,'1988-11-21'),
// ('Israel','Williamson','Rae48@gmail.com','{"country": "Morocco", "province": "Arkansas", "canton": "North Jan"}',9,'1966-11-12'),
// ('Virgil','Kirlin','Cora_Stamm@hotmail.com','{"country": "Sierra Leone", "province": "Massachusetts", "canton": "Herzogchester"}',0,'1989-11-20'),
// ('Arnulfo','Hagenes','Loma4@hotmail.com','{"country": "Niger", "province": "Arizona", "canton": "Danielland"}',9,'1960-02-06'),
// ('Margie','Keeling','Rhiannon78@gmail.com','{"country": "Tunisia", "province": "Wisconsin", "canton": "North Rae"}',0,'1986-06-16'),
// ('Mary','VonRueden','Jany.Champlin@gmail.com','{"country":"Sweden", "province": "Mississippi", "canton": "Garnettberg"}',0,'1999-12-05'),
// ('Alessandro','Leffler','Eldred.Hansen@gmail.com','{"country": "Lebanon", "province": "Iowa", "canton": "Fletcherfurt"}',2,'1991-09-30'),
// ('Aylin','Medhurst','Bernard_Yost67@hotmail.com','{"country": "Somalia", "province": "Colorado", "canton": "Leannonland"}',2,'1966-04-14'),
// ('Filiberto','Borer','Karen_Stamm25@hotmail.com','{"country": "Angola", "province": "South Carolina", "canton": "Sengerton"}',0,'1983-09-04'),
// ('Isaiah','Wolff','Dwight.Jerde18@yahoo.com','{"country": "Papua New Guinea", "province": "Oregon", "canton": "New Dandreborough"}',0,'1982-04-01'),
// ('Garret','Crona','Destini56@yahoo.com','{"country": "Guinea-Bissau", "province": "Oklahoma", "canton": "Lake Mackstad"}',9,'1992-04-02'),
// ('Tom','Predovic','Nedra13@gmail.com','{"country": "Uganda", "province": "Montana", "canton": "Morissettetown"}',1,'1994-05-24'),
// ('Kyla','Hettinger','Otho68@hotmail.com','{"country": "Niue", "province": "Kentucky", "canton": "McKenzieton"}',2,'1981-04-23'),
// ('Bernadine','Hagenes','Jennifer_Moore@hotmail.com','{"country": "Montenegro", "province": "Maryland", "canton": "South Germanstad"}',9,'1995-04-02'),
// ('Elwyn','Bradtke','Ola.Zboncak@yahoo.com','{"country": "Reunion", "province": "Virginia", "canton": "New Ashlynntown"}',0,'1967-04-04'),
// ('Wava','Hilll','Lauretta0@yahoo.com','{"country": "Cyprus", "province": "South Carolina", "canton": "Jacquesville"}',1,'1985-07-17'),
// ('Prudence','Langosh','Josephine_Kunde@yahoo.com','{"country": "Saint Pierre and Miquelon", "province": "Virginia", "canton": "Andersonview"}',9,'1991-07-20'),
// ('Adrien','Monahan','Lexie_Gislason88@hotmail.com','{"country": "Zambia", "province": "Louisiana", "canton": "New Gretchenland"}',2,'1989-08-25'),
// ('Felicia','Kautzer','Lola_Collins11@yahoo.com','{"country": "Syrian Arab Republic", "province": "Illinois", "canton": "North Blair"}',0,'1979-06-05'),
// ('Sydney','Parker','Jarvis96@gmail.com','{"country": "Vanuatu", "province": "South Dakota", "canton": "Irwinton"}',0,'1979-01-14'),
// ('Raquel','Herzog','Elissa.Balistreri35@hotmail.com','{"country": "Botswana", "province": "Colorado", "canton": "Blandaview"}',9,'1969-03-06'),
// ('Deonte','Bechtelar','Junius_Klein@hotmail.com','{"country": "Turks and Caicos Islands", "province": "Nebraska", "canton": "East Karimouth"}',0,'1988-01-28'),
// ('Lempi','Wiza','Felton_Brekke@yahoo.com','{"country": "Uruguay", "province": "Delaware", "canton": "Goyettestad"}',9,'1987-05-29'),
// ('Ruth','Brown','Baylee.Connelly@gmail.com','{"country": "Serbia", "province": "Washington", "canton": "Anitaport"}',9,'1960-07-10'),
// ('Silas','Kub','Jaleel_Little86@yahoo.com','{"country": "Hungary", "province": "Pennsylvania", "canton": "East Muriel"}',9,'1997-11-16'),
// ('Geovanni','Bogisich','Felicia.Prosacco49@gmail.com','{"country": "Mozambique", "province": "North Dakota", "canton": "Kshlerinville"}',0,'1970-04-16'),
// ('Marlen','Nitzsche','Robert_Effertz@hotmail.com','{"country": "San Marino", "province": "Arkansas", "canton": "NorthMabelview"}',1,'1966-10-10'),
// ('Vicky','Gutmann','Nicole.Kertzmann36@yahoo.com','{"country": "Monaco", "province": "South Carolina", "canton": "Israelburgh"}',9,'1982-08-03'),
// ('Lane','Walsh','Jaren0@yahoo.com','{"country": "Austria","province": "Arkansas", "canton": "Huelhaven"}',0,'1989-03-19'),
// ('Scarlett','Considine','Eileen_Waelchi@hotmail.com','{"country": "Falkland Islands (Malvinas)", "province": "Colorado", "canton": "Blicktown"}',2,'1970-04-01')
